apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-7yfm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-7yfm
    app.kubernetes.io/part-of: ci10t-777-0047-app
  name: devfile-sample-7yfm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-7yfm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-7yfm
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0047-tenant/ci10t-777-0047-app/devfile-sample-7yfm@sha256:134b97cab16afbe56c28953fef6195fcbe00632e0c2e8d959b55a6086394d087
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
